# Generated by Django 2.2 on 2022-11-04 20:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="created",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="updated",
        ),
    ]
